version: "2"

formatters:
  enable:
    - gofumpt
    - goimports

linters:
  disable:
    - errcheck
  enable:
    - govet
    - ineffassign
    - staticcheck
    - unused
    - misspell
    - revive
    - errorlint
    - godot
    - noctx
  settings:
    revive:
      rules:
        - name: exported
          disabled: true

issues:
  max-same-issues: 0
